spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zaiqi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  data:
    redis:
      host: localhost
      port: 6379
      password: ky004
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4

logging:
  level:
    com.zaiqi: DEBUG
